### ISSUE TITLE
Support style in console

### ISSUE THREAD

**Issue by Jinkwon** [B1naryStudio/js-mobile-console#11]
Hi,

In Chrome, can styling to logs.
Could you support such as features?
![2016-05-20 1 28 09](https://cloud.githubusercontent.com/assets/1798916/15417257/b6b6b868-1e8e-11e6-83f9-049e43b2a327.png)

**Comment by msemenistyi** [comment]
Hi, @Jinkwon ! Thanks for the suggestion, I will consider it

**Comment by msemenistyi** [comment]
The feature is included in the v0.4.0
